server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:8080/jesus
  jpa:
    show-sql: true
  application:
    name: Jesus
  cache:
    ehcache:
      config: classpath:ehcache.xml
logging:
  level:
    root: WARN
    org:
      springframework:
        web: INFO
      hibernate: ERROR